In [1]:
print("hello")

hello


In [15]:

import tensorflow as tf # When we import TensorFlow, a default graph is made

hello = tf.constant("Hello, TensorFlow!") # Add a constant-operation to the (default) graph
sess = tf.Session() # Create a session from which to run the graph
print(sess.run(hello))
sess.close()






b'Hello, TensorFlow!'


In [16]:
a = tf.constant(3.0, dtype=tf.float32) # add a constant-op to the graph
b = tf.constant(4.0, dtype=tf.float32) # add another constant-op to the graph
sum_a_b = tf.add(a,b) # create a TensorFlow op that adds tensors a,b and produces a new tensor
sess = tf.Session()
print(sess.run(sum_a_b))
sess.close()

7.0



config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

In [19]:
# Configure a session to not use too much GPU memory
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

# Create the actual session. The config argument is only necessary if you have defined a configuration, like above
sess = tf.Session(config=config)
with tf.Session(config=config) as sess:
    print(sess.run(sum_a_b))
    # the session will close when we leave the with-block

7.0


In [20]:
with tf.Session(config=config) as sess:
    first_const, sum_result = sess.run([a, sum_a_b])
    print("The first constant tensor has value: {}".format(first_const))
    print("The result of the add operation has value: {}".format(sum_result))

The first constant tensor has value: 3.0
The result of the add operation has value: 7.0


In [21]:
x = tf.constant([[1.0], [2.0]], dtype=tf.float32) # tf.matmul requires both arguments be >= rank-2
W = tf.constant([[3.0, 4.0], [5.0, 6.0]], dtype=tf.float32)
y = tf.matmul(W, x) # perform matrix-vector multiplication W * x

with tf.Session() as sess:
    print(sess.run(y))

[[11.]
 [17.]]


In [22]:
x = tf.placeholder(tf.float32, shape=[2,1])
W = tf.constant([[3.0, 4.0], [5.0, 6.0]], dtype=tf.float32)
y = tf.matmul(W, x)
with tf.Session() as sess:
    print("x is [[1.0], [2.0]]:")
    print(sess.run(y, feed_dict={x: [[1.0], [2.0]]})) # input a feed_dict for placeholder x -- must be at least rank-2!
    print("x is [[2.0], [4.0]]:")
    print(sess.run(y, feed_dict={x: [[2.0], [4.0]]})) # we can change input to graph from here

x is [[1.0], [2.0]]:
[[11.]
 [17.]]
x is [[2.0], [4.0]]:
[[22.]
 [34.]]


In [23]:
x = tf.placeholder(tf.float32, shape=[2,1])
init_value = tf.random_normal(shape = [2, 2]) # will draw a 2 x 2 matrix with entries from a standard normal distn
W = tf.Variable(init_value) # Within the graph, initialize W with the values drawn from a standard normal above
y = tf.matmul(W, x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) # necessary step now that we have variables
    print("Our random matrix W:\n")
    print(sess.run(W)) # Notice that we don't have to use a feed_dict here, because x is not part of computing W
    print("\nResult of our matrix multiplication, y:\n")
    print(sess.run(y, feed_dict={x: [[1.0], [2.0]]}))

Our random matrix W:

[[ 0.33080715 -1.2375599 ]
 [-1.4252274   0.11490628]]

Result of our matrix multiplication, y:

[[-2.1443126]
 [-1.1954148]]


In [24]:
x = tf.placeholder(tf.float32)
W = tf.get_variable(name="W", shape = [2, 2], initializer=tf.random_normal_initializer) # note we give the variable a name
y = tf.matmul(W, x)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    print(sess.run(y, feed_dict={x: [[1.0], [2.0]]}))

[[-0.42861283 -1.4329536 ]
 [-0.11271913 -0.40823394]]
[[-3.29452 ]
 [-0.929187]]
